### ISSUE TITLE
Problems with the trained ResNet-101 and ERFNet

### ISSUE THREAD

**Issue by Adyoshkin** [cardwing/Codes-for-IntRA-KD#1]
I can't get .pth file from archive:"tar: This does not look like a tar archive". Can you check your files on google drive?

**Comment by cardwing** [comment]
You don't need to untar the file. Just put the weight in the desired folder and run the testing script.

**Comment by cardwing** [comment]
See [this line](./test_pspnet_multi_scale.sh#L5) in the testing script of ResNet-101.

**Comment by Adyoshkin** [comment]
Thanks!
